/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 gamepad.gltf --transform
Author: Mikkel Garde Blaase (https://sketchfab.com/plorigon)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nintendo-switch-diorama-7bafb356e4f34695954da8fa6cd640b4
Title: Nintendo Switch Diorama
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/gamepad-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Outline_Mesh002_black_outline_0.geometry} material={materials.black_outline} rotation={[0.059, -0.263, -0.127]} scale={0.01} />
      <mesh geometry={nodes.Outline_Mesh002_BaseCol_0.geometry} material={materials.BaseCol} rotation={[0.059, -0.263, -0.127]} scale={0.01} />
      <mesh geometry={nodes.Outline_Mesh002_Opacity_Stuff_0.geometry} material={materials.Opacity_Stuff} rotation={[0.059, -0.263, -0.127]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/gamepad-transformed.glb')
