/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 trailer.gltf --transform
Author: Alena Shek (https://sketchfab.com/ShekAlena)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trailer-040ad3bbf0c54098b90a87ac517d3901
Title: Trailer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/trailer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['0208trailer_default']} rotation={[-Math.PI / 2, 0, 6]} scale={0.04} />
    </group>
  )
}

useGLTF.preload('/trailer-transformed.glb')
